config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}

  devise_for :users, only:[:create, :update],
    controllers: { registrations: 'registrations' }

  resources :played_instruments, only: [:create, :destroy, :new]
  #get "add_instruments", to: "users#add_instruments"

  resources :users, only: [:show, :edit, :index, :update]

  resources :conversations do
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :appointments, only: [:new, :create, :show]
  end

  resources :appointments, only: [:index, :destroy]
  get '/conversations/:id/refresh_messages', to: 'conversations#refresh_messages', as: 'refresh_messages'
  # devise_for :users

  mount Attachinary::Engine => "/attachinary"

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user1, :class_name => "User", :foreign_key => "user_1_id"
  belongs_to :user2, :class_name => "User", :foreign_key => "user_2_id"
  has_many :messages, dependent: :destroy
  has_many :appointments, dependent: :destroy
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:refresh_messages, :destroy, :show]
  def new
    @conversation = Conversation.new
    @conversation.user1 = current_user
  end

  def create

    other_user = User.find(params[:conversation][:user2].to_i)


    first_posibility = Conversation.where(user1: current_user, user2: other_user)
    second_posibility = Conversation.where(user2: current_user, user1: other_user)

    if first_posibility.length.zero? && second_posibility.length.zero?

      @conversation = Conversation.new()

      @conversation.user1 = current_user
      @conversation.user2 = other_user

      respond_to do |format|
        if @conversation.save
          format.html { redirect_to conversation_path(@conversation), notice: 'Conversation was successfully created.' }
        else
          format.html { render :new }
        end
      end

    else

      if !first_posibility.length.zero?
        redirect_to conversation_path(first_posibility.last)
      else
        redirect_to conversation_path(second_posibility.last)
      end

    end
  end

  def index
    @conversations = Conversation.where("user_1_id = ? or user_2_id = ?", current_user.id, current_user.id)
  end

  def show
      set_conversation
      @message = Message.new
  end

  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
    end
  end

  def refresh_messages
    if !params[:last_message_id].nil? &&
     last_message = @conversation.messages.find(params[:last_message_id])
     @messages = @conversation.messages.where("created_at > ?", last_message.created_at)
    else
      @messages = @conversation.messages
     respond_to do |format|
       format.js
     end
    end
  end

  private

  def set_conversation
    @conversation = Conversation.find(params[:id])
  end

end

app/views/conversations/_form.html.erb
<%= simple_form_for(@conversation) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
  <%= f.input :user2, collection: User.all.map{ |u| ["#{u.first_name} #{u.last_name}", u.id, { class: u.id}] }, label: "To: ", label_html: {id: 'instrument-input'}, input_html: { class: 'input', id: 'white-color' } %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "CREATE CONVERSATION", class: 'btn btn-primary input' %>
  </div>
<% end %>

app/views/conversations/index.html.erb
<div class="background" style="background-image: url('<%= image_path "blue_background.jpg" %>');"> </div>
<div class="container margin-top">
  <p id="notice"><%= notice %></p>
    <div class="row">
      <div class="xs-col-12">
        <div class="new-conversation">
          <h2>MY</h2> <h2>CONVERSATIONS</h2>
        </div>
        <% @conversations.each do |conversation| %>
        <% if conversation.user1 == current_user %>
        <% recipient = conversation.user2 %>
        <% elsif conversation.user2 == current_user%>
        <% recipient = conversation.user1 %>
        <% end %>
        <div class="card-conversations">
          <div class="flexbox-title-conv">
            <%= recipient.first_name %> <%= recipient.last_name %>
          </div>
        <div class="picture-conv" style="background-image: url('<%= recipient.facebook_picture_url || cl_image_path(recipient&.photo&.path || "http://placehold.it/30x30") %>');">

        </div>
        <div class="last-message">
          <% if Message.where(conversation_id: conversation.id).empty? %>
            <p> no messages yet </p>
          <% else %>
            <p><%= truncate(Message.where(conversation_id: conversation.id).order('created_at DESC').first.content, length: 65, omission: "...") %></p>
          <% end %>
        </div>
          <%= link_to conversation, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-times cross" aria-hidden="true"></i>
          <% end %>
          <%= link_to '', conversation_path(conversation), class: 'conv-link' %>
      </div>
    <% end %>
    <div class="flex-button-container">
      <%= link_to 'New Conversation', new_conversation_path, class: 'btn btn-primary new-link' %>
    </div>
    </div>
  </div>
</div>

app/views/conversations/new.html.erb
<div class="background" style="background-image: url('<%= image_path "blue_background.jpg" %>');"> </div>
<div class="container conversation-form margin-top">
  <div class="row margin-left-new">
    <div class="col-xs-12">
      <h2 class="margin-top">NEW</h2>
      <h2 class="margin-shrink">CONVERSATION</h2>

      <%= render 'form', conversation: @conversation %>
    </div>
  </div>
</div>

app/views/conversations/refresh_messages.js.erb
<% if !@messages.nil? %>
  <% @messages.each do |message| %>
    var msg_selector = $("#message_<%= message.id %>");
    $(msg_selector).remove();
    var msg = "<%= j render 'messages/show', message: message %>";
    $('#messages-list').append(msg);
  <% end %>
<% end %>

app/views/conversations/show.html.erb
<div class="white-background" style="background-image: url('<%= asset_path "white_background.png" %>');"></div>

<%= link_to "", new_conversation_appointment_path(@conversation), class: "fa fa-calendar cross appointment-link" %>

<div class="chat-wrapper">
  <div class="container container-chat" id="messages-list" >
  <% @conversation.messages.each do |message| %>
    <%= render "messages/show", message: message %>
  <% end %>
  </div>
  <div class="form-message">
  <%= simple_form_for [@conversation, @message], :url => conversation_messages_path(@conversation), html: { id: "newMessage", class: "chat-form fixed bottom"}, method: "post", remote: true do |f| %>
      <%= f.text_field :content, id: "chat-field", placeholder: "Type your message..." %>
      <%= f.hidden_field :user_id, value: "current_user.id" %>
      <%= f.hidden_field :conversation_id, value: params[:conversation_id] %>
      <%= f.submit "Send", class: "btn btn-send"%>
  <% end %>
</div>


<%= content_for(:after_js) do %>

  <script>
    $(document).ready(function() {
      scrollToBottom();
      setInterval(refreshMessages, 500);

      function scrollToBottom(){
        var d = $('body');
        d.scrollTop(d.prop("scrollHeight"));
      }
      function refreshMessages() {
        if($("#messages-list .message").length > 0) {
          var lastMessage = $("#messages-list .message").last().data("messageId");
          $.ajax({
            url: "<%= j refresh_messages_path(@conversation) %>",
            data: {last_message_id: lastMessage},
          });
        } else {
          $.ajax({
            url: "<%= j refresh_messages_path(@conversation) %>",
          });
        }
      }

      $('.btn-send').click(function(){
        $('html, body').animate({scrollTop: $(document).height()},"slow");
      });
    });
  </script>
<% end %>