config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}

  devise_for :users, only:[:create, :update],
    controllers: { registrations: 'registrations' }

  resources :played_instruments, only: [:create, :destroy, :new]
  #get "add_instruments", to: "users#add_instruments"

  resources :users, only: [:show, :edit, :index, :update]

  resources :conversations do
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :appointments, only: [:new, :create, :show]
  end

  resources :appointments, only: [:index, :destroy]
  get '/conversations/:id/refresh_messages', to: 'conversations#refresh_messages', as: 'refresh_messages'
  # devise_for :users

  mount Attachinary::Engine => "/attachinary"

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible margin-top flashes" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible flashes" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar-medlii">
    <div class="sidebar-btn">
      <span></span>
      <span></span>
      <span></span>
    </div>
<div class="flex-title-navbar">
    <div class="navbar-title">medlii.</div>
</div>

    <% current_uri = request.env['PATH_INFO'] %>
<% if current_uri == users_path %>
    <div id = "logo-medlii" class="navbar-search-logo" style=" background-image: url('<%= asset_path "medlii_blue_logo.png" %>');"> </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<% if user_signed_in? %>
<div class="sidebar">
  <div class="sidebar-decoration" style=" background-image: url('<%= asset_path "blue_background.jpg" %>');">
    <div class="sidebar-people" style=" background-image: url('<%= asset_path "sidebar_people.png" %>');"> <span id="medlii-sidebar">medlii.</span> </div>
    <div id="cross-sidebar"> <i class="material-icons">clear</i></div>
  </div>

  <div class="links-sidebar">
    <%= link_to 'APPOINTMENTS', appointments_path, class: 'link-sidebar', id: 'appointments' %>
    <%= link_to 'MESSAGES', conversations_path, class: 'link-sidebar', id: 'messages' %>
    <%= link_to 'SEARCH', users_path, class: 'link-sidebar', id: 'search' %>
    <%= link_to 'MY MEDLII', user_path(current_user), class: 'link-sidebar', id: 'mymedlii' %>
    <%= link_to 'LOG OUT', destroy_user_session_path, class: 'link-sidebar', id: 'logout', method: :delete %>
  </div>
</div>


<% content_for :after_js do %>

<script>
  current_url = window.location.pathname

  if(current_url === "<%= users_path %>"){
    $('#search').addClass('active');
  }

  <% if @user %>
  if(current_url === "<%= user_path(@user) %>" && <%= @user.id != current_user.id %>){
    $('#search').addClass('active');
  }

  if(current_url === "<%= user_path(current_user) %>" && <%= @user.id == current_user.id %>){
    $('#mymedlii').addClass('active');
  }
  <% end %>

  if(current_url === "<%= conversations_path %>" || current_url === "<%= new_conversation_path %>"){
    $('#messages').addClass('active');
  };


  if(current_url === "<%= appointments_path %>"){
    $('#appointments').addClass('active');
  }

</script>

<% end  %>
<% end %>