config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}

  devise_for :users, only:[:create, :update],
    controllers: { registrations: 'registrations' }

  resources :played_instruments, only: [:create, :destroy, :new]
  #get "add_instruments", to: "users#add_instruments"

  resources :users, only: [:show, :edit, :index, :update]

  resources :conversations do
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :appointments, only: [:new, :create, :show]
  end

  resources :appointments, only: [:index, :destroy]
  get '/conversations/:id/refresh_messages', to: 'conversations#refresh_messages', as: 'refresh_messages'
  # devise_for :users

  mount Attachinary::Engine => "/attachinary"

end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user, :foreign_key => "user_id"
  belongs_to :conversation
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def other_user
    User.find(user_2_id)
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :destroy]

  def index
    @appointments = Appointment.where("user_1_id = ? or user_2_id = ?", current_user.id, current_user.id)
  end

  def new
    @appointment = Appointment.new
    @conversation = Conversation.find(params[:conversation_id])
  end

  def create
    @conversation = Conversation.find(params[:conversation_id])

    @appointment = Appointment.create(appointment_params)
    @appointment.user_id = current_user.id
    @appointment.user_2_id = @conversation.user_2_id
    @appointment.conversation_id = @conversation.id

    @appointment.save!
    redirect_to appointments_path
  end

  def show
    # set_appointment
    # @appointment = Appointment.new
  end

  def destroy
    @appointment.destroy
    redirect_to :back
  end


  private
  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def set_conversation
    @conversation = Conversation.find(params[:conversation_id])
  end

  def appointment_params
    params.require(:appointment).permit(:address, :date)
  end
end

app/views/appointments/_form.html.erb
<%= simple_form_for([@conversation, @appointment], html: { method: :post }) do |f| %>

<div class="form_for_appointment">
  <%= f.input :address, as: :string, label: "Where do you want to meet?", placeholder: "5333 Casgrain Ave",id: 'appointment_address', input_html: { class: "white-colored" } %>
  <%= f.input :date, as: :datetime, start_year: Date.today.year, end_year: Date.today.year + 110, order: [:day, :month, :year], input_html: { class: "white-colored" }, html_classes: { class: "flex-datetime"}, label_html: { class: "flex-label" }, label: "<span>Date</span> <span>Time</span>".html_safe %>

  <%= f.hidden_field :user_id, value: "current_user.id" %>
  <%= f.hidden_field :conversation_id, value: params[:conversation_id] %>
<div class="flex-button-container">
<%= f.button :submit, "Let's play!", class: 'btn btn-raise btn-primary' %>
</div>
</div>
<% end %>

app/views/appointments/create.html.erb
<h1>Appointments#create</h1>
<p>Find me in app/views/appointments/create.html.erb</p>

app/views/appointments/index.html.erb
<div class="background" style="background-image: url('<%= image_path "blue_background.jpg" %>');"> </div>
<div class="container margin-top">
  <div class="row">
    <div class="col-xs-12">

    <div class="new-conversation">
      <h2>MY</h2> <h2>APPOINTMENTS</h2>
    </div>
            <% current_user.appointments.each do |appointment| %>
            <% if appointment.other_user.photo.nil? %>
            <% avatar_url = appointment.other_user.facebook_picture_url || "http://placehold.it/30x30" %>
            <% else %>
            <% avatar_url = appointment.other_user.facebook_picture_url || cl_image_path(appointment.other_user.photo.path) || "http://placehold.it/30x30" %>
          <% end %>
            <div class="card-conversations">
          <div class="flexbox-title-conv">
            <%= appointment.other_user.first_name %> <%= appointment.other_user.last_name %>
          </div>
        <div class="picture-conv" style="background-image: url('<%= avatar_url %>');"></div>
        <div class="address-card">
          <p> <%= appointment.address %></p>
        </div>
          <div class="datetime-card">
           <p> <%= appointment.date.to_time.strftime('%B %e at %l:%M %p') %></p>
          </div>
      <%= link_to appointment, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-times cross" aria-hidden="true"></i>
          <% end %>
      </div>

<% end %>




  </div>
  </div>
</div>

app/views/appointments/new.html.erb
<div class="background" style="background-image: url('<%= image_path "blue_background.jpg" %>');"> </div>

<div class="container margin-top">
  <div class="row">
    <div class="xs-col-12">
      <div class="new-conversation">
        <h2>NEW</h2> <h2>APPOINTMENT</h2>
      </div>

      <%= render 'form', appointment: @appointment %>


    </div>
  </div>
</div>

<% content_for :after_js do %>
<script>
  $('.form-inline').addClass('flex-datetime')
</script>
<% end %>

app/views/appointments/show.html.erb
<h3>My appointments <h3>

<%= link_to "All my appointments " , conversation_appointments_path(@conversation, @appointment) %>
<div class = "text-center">
<% current_user.appointments.each do |appointment| %>

  <ul>
  <li> Where we will meet: <%= appointment.address %></li>
  <li> When: <%= appointment.date %></li>
  </ul>
<% end %>
</div>